# Generated by Django 4.1 on 2022-09-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha_posteo',
            field=models.DateField(auto_now_add=True),
        ),
    ]
