# Generated by Django 4.1 on 2022-09-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0004_alter_blog_fecha_posteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='id_blog',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
