# Generated by Django 4.1 on 2022-09-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0005_blog_id_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='texto',
            new_name='cuerpo',
        ),
        migrations.AddField(
            model_name='blog',
            name='autor',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
