# Generated by Django 4.1 on 2022-09-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0006_rename_texto_blog_cuerpo_blog_autor_blog_subtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
