# Generated by Django 4.1 on 2022-09-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0008_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='fecha_posteo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
