# Generated by Django 4.1 on 2022-09-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogs', '0011_alter_blog_autor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
